apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30001
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: brunomarques1/fastapi
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_NAME
        - name: MSG
          valueFrom:
            configMapKeyRef:
              name: mensagem
              key: MSG
            
